### ISSUE TITLE
problem with javascript scripts (?) 

### ISSUE THREAD

**Issue by JohnGriffiths** [mindcruzer/pelican-encrypt-content#5] opened 2015-09-09 14:46 UTC
Hi. 

The plugin is really excellent. 

However an issue I have found is that it seems to prevent tools such as mathjax and bigfoot.js from rendering properly on password-protected pages. This a real problem for me as I have 
a lot of equations on some of my pages, and without proper mathjax rendering it leaves the content pretty useless. 

I'm afraid I am almost completely ignorant of javascript (I _think_ this is a javascript problem, although not certain); so can't really troubleshoot this much myself.  Do you agree with my diagnosis and do you know of a fix?

Ta.

**Comment by mindcruzer** [comment] 2015-09-09 18:44
Is the source simply not rendering (ex. with MathJax you still see the $$ or [\ delimiters)?

**Comment by JohnGriffiths** [comment] 2015-09-09 18:54
Yes I think it is just not rendering

So I get text on the page like: 

\(D(\mathrm{d}/\mathrm{d}t)\) - differential operator
\(\varphi\) - state variable
\(\alpha\) - external inputs

**Comment by mindcruzer** [comment] 2015-09-10 03:24
The issue is that MathJax will not re-render any new content that appears on the page. I took some time today to re-write the plugin. It's a lot simpler since there is no need to modify any templates. Set it up with your pelican installation (assuming you're using Pelican 3.6).

Once you've got that done, you need to open up `decrypt-form.tpl.html` and find these lines near the bottom of the file:

```javascript
...
if (content) {
    decrypted_content.innerHTML = content;
    decrypt_form.parentNode.removeChild(decrypt_form);
    encrypted_content.parentNode.removeChild(encrypted_content);
}
else {
    password_input.value = '';
}
...
```
change it to this (added nested if statement):


```javascript
...
if (content) {
    decrypted_content.innerHTML = content;
    decrypt_form.parentNode.removeChild(decrypt_form);
    encrypted_content.parentNode.removeChild(encrypted_content);

    if (window.MathJax) {
        MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
    }
}
else {
    password_input.value = '';
}
...
```
This will tell MathJax to re-scan the page when the content is decrypted, and you should see your equations render properly.

**Comment by JohnGriffiths** [comment] 2015-09-10 16:29
Thanks. 

However currently with the new version `make html` is erroring with the following:

`Traceback (most recent call last):  `
`File "/home/jgriffiths/Virtualenvs/_ipython2.4/bin/pelican", line 11, in <module>  sys.exit(main())  `
`File "/home/jgriffiths/Virtualenvs/_ipython2.4/local/lib/python2.7/site-packages/pelican/__init__.py", line 386, in main  pelican, settings = get_instance(args)  `
`File "/home/jgriffiths/Virtualenvs/_ipython2.4/local/lib/python2.7/site-packages/pelican/__init__.py", line 380, in get_instance  return cls(settings), settings  `
`File "/home/jgriffiths/Virtualenvs/_ipython2.4/local/lib/python2.7/site-packages/pelican/__init__.py", line 58, in __init__  signals.initialized.send(self)  `
`File "/home/jgriffiths/Virtualenvs/_ipython2.4/local/lib/python2.7/site-packages/blinker/base.py", line 267, in send   for receiver in self.receivers_for(sender)]  `
`File "encrypt_content/encrypt_content.py", line 85, in pelican_initialized       
  settings.update(pelican_obj.settings['ENCRYPT_CONTENT'])   `
`KeyError: 'ENCRYPT_CONTENT'  `
`make: *** [html] Error 1  `

**Comment by mindcruzer** [comment] 2015-09-10 17:18
Grab the latest version, it should be fixed.

**Comment by JohnGriffiths** [comment] 2015-09-10 17:24
Ah, excellent. Was just about to say I realized that it was because I hadn't added those lines to pelicanconf.py. 

All working now :) :) :) 

Great stuff!

**Comment by JohnGriffiths** [comment] 2015-09-10 17:39
Another Q on this topic: 

Two other js plugins that I use on my site that seem to be disabled in encrypted content: 

jquery slidetoggle (described [here](http://joergdietrich.github.io/notebook-collapse-input.html))

bigfoot.js ([website](http://www.bigfootjs.com); I am using it the same as [this blog](http://themodernscientist.com/posts/2013/2013-06-02-my_octopelican_python_blog) )

Would a similar fixes be needed to  `decrypt-form.tpl.html` to get these working for decrypted entries?

**Comment by mindcruzer** [comment] 2015-09-10 18:01
The issue with bigfoot is the same. The plugin scans the page once after it loads, and then never checks again unless manually told to do so. For example, with bigfoot, it looks like the plugin is initialized with the `$.bigfoot()` call, so you might try adding the following statement just below the one for MathJax:

```javascript
if (window.$ && $.bigfoot) {
    $.bigfoot();
}
```
(no guarantees that will work--I'm not familiar with the plugin)

As for slideToggle, the author that made the changes to that liquid_tags plugin needs to make a modification to his code (or you can do this to your copy, but that is less ideal). 

This line:
https://github.com/joergdietrich/pelican-plugins/blob/collapse-code/liquid_tags/notebook.py#L166

Needs to be changed to:

```javascript
$('body').on('click', 'div.collapseheader', function () {
```
I am taking a wild guess with this one since I am again not familiar with the plugin, I just did a quick scan of the source.

**Comment by JohnGriffiths** [comment] 2015-09-10 19:02
Cheers!

So: 

the wild guess for jquery was right on the mark; your suggested change makes slide toggling work on decrypted pages. 

The bigfoot hack doesn't seem to be making any difference though.

**Closed** 2020-05-25 16:57 UTC
