### ISSUE TITLE
Article content is not encrypted 

### ISSUE THREAD

**Issue by aoplabs** [mindcruzer/pelican-encrypt-content#18] opened 2020-12-01 15:59 UTC
I am facing a problem where, the change to article title is works fine but the article content shows the original content. 

I tried to debug the `encrypt_content()` method. The method sets  `content._content`  correctly.  Looks to me somewhere it is overwritten to original content. 

I currently have the following plugins activated 
````
-> Plugins found:
  | pelican.plugins.render_math
  | pelican.plugins.encrypt_content
````

````
pelican --version
4.5.0
````

**Comment by mindcruzer** [comment] 2020-12-05 19:28
I tried this on my end with `render_math` installed but I was unable to reproduce it. From what I saw it was encrypting the content but once decrypted the math doesn't render (which can likely be fixed by adding some JS to get MathJax to re-render after decryption). 

Whats the pelican version you're using?

**Comment by aoplabs** [comment] 2020-12-09 10:39
Pelican version `4.5.0` . I have found an arbitrary work around that fixes my issue but I am able to reproduce in following way.

`PLUGINS = ['encrypt_content', 'render_math']` : Works

`PLUGINS = ['render_math', 'encrypt_content']` : Doesn't work

Pelican auto discovery: Doesn't work

**Closed** 2021-08-07 01:21 UTC
